// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildGeocode(arg1:string):Promise<void>;

export function BuildGraph():Promise<void>;

export function Config():Promise<Record<string, any>>;

export function CreateToken(arg1:string,arg2:number):Promise<string>;

export function GetEnv():Promise<main.Env>;

export function Health(arg1:number):Promise<main.Health>;

export function ServerRunning():Promise<boolean>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
