// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildGeocode(arg1) {
  return window['go']['main']['App']['BuildGeocode'](arg1);
}

export function BuildGraph() {
  return window['go']['main']['App']['BuildGraph']();
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function CreateToken(arg1, arg2) {
  return window['go']['main']['App']['CreateToken'](arg1, arg2);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function Health(arg1) {
  return window['go']['main']['App']['Health'](arg1);
}

export function ServerRunning() {
  return window['go']['main']['App']['ServerRunning']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
